//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.YodaSpeak {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YodaSpeakRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YodaSpeakRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.YodaSpeak.YodaSpeakRes", typeof(YodaSpeakRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string EnpointHeader {
            get {
                return ResourceManager.GetString("EnpointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Mashape-Key.
        /// </summary>
        internal static string MashapeKey {
            get {
                return ResourceManager.GetString("MashapeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yoda?sentence=.
        /// </summary>
        internal static string MashapeParam {
            get {
                return ResourceManager.GetString("MashapeParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2dtutDcMdfmshiSHV7kpJEnOaPSIp1g1N0zjsncI0JQz3wPX4k.
        /// </summary>
        internal static string YodaSpeakAPI {
            get {
                return ResourceManager.GetString("YodaSpeakAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yoda.p.mashape.com/.
        /// </summary>
        internal static string YodaSpeakEndPointURL {
            get {
                return ResourceManager.GetString("YodaSpeakEndPointURL", resourceCulture);
            }
        }
    }
}
